function y = StopbandFilter(x,  fs)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 23-Oct-2019 15:05:01

persistent Hd;

if isempty(Hd)
    
    Fpass1 = 3500;% stop1;   % First Passband Frequency
    Fstop1 = 4000;%stop1 + stop1.*0.01;   % First Stopband Frequency
    Fstop2 = 4300;%stop2 - stop2*0.01;   % Second Stopband Frequency
    Fpass2 = 4800;%;stop2;   % Second Passband Frequency
    Apass1 = 1;      % First Passband Ripple (dB)
    Astop  = 120;     % Stopband Attenuation (dB)
    Apass2 = 1;      % Second Passband Ripple (dB)
    Fs     = fs;  % Sampling Frequency
    
    h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
        Fstop2, Fpass2, Apass1, Astop, Apass2, Fs);
    
    Hd = design(h, 'equiripple');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

